-- src/main/resources/db/migration/V1__Create_Location_Table.sql

CREATE TABLE public.location (
    id bigint generated by default as identity,
    guuid uuid NOT NULL,
    name varchar(255),
    description varchar(255),
    latitude float(53),
    longitude float(53),
    coordinates geometry(Point,4326),
    primary key (id)
);
