-- src/main/resources/db/migration/V1__Create_Users_Table.sql

CREATE TABLE public.users (
    id bigint generated by default as identity,
    guuid uuid NOT NULL,
    email varchar(255),
    password varchar(255),
    username float(53),
    primary key (id)
);
