-- src/main/resources/db/migration/V1__Create_Location_Table.sql

CREATE TABLE public.location (
    id bigint generated by default as identity,
    name varchar(255),
    coordinates geometry(Point,4326),
    primary key (id)
);
