schema-version = "0.2"

[[build.env]]
name = "BP_NODE_ENV"
value = "production"

[[build.env]]
name = "BP_NODE_PROJECT_PATH"
value = "."

[[build.env]]
name = "BP_NODE_OPTIONS"
value = "--no-warnings"

[[build.env]]
name = "BP_NODE_VERBOSE"
value = "true"

[[build.env]]
name = "BP_NODE_USE_AT_RUNTIME"
value = "true"

[[build.env]]
name = "BP_NODE_RUN_SCRIPTS"
value = "false"

[[build.env]]
name = "BP_NPM_INSTALL"
value = "false"

[[build.env]]
name = "BP_NPM_CI"
value = "false"

[[build.env]]
name = "BP_NPM_RUN_BUILD"
value = "false"

[[build.env]]
name = "BP_NPM_REBUILD"
value = "false"

[[build.env]]
name = "BP_NODE_MODULES_CACHE"
value = "false"

[[build.env]]
name = "BP_NPM_CACHE"
value = "false"

[[build.env]]
name = "BP_CACHE"
value = "false"

[[build.env]]
name = "BP_LAUNCH_COMMAND"
value = "npm start"

[[processes]]
type = "web"
command = "npm start"
direct = true

[build]
exclude = ["node_modules", ".next", ".turbo", "package.json", "package-lock.json"]
